# Generated by Django 3.1 on 2020-08-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ispn_number',
            new_name='isbn_number',
        ),
    ]
